begin;
create extension if not exists pgtap with schema extensions;
select plan(78);

select has_schema('academic','academic schema exists');
select has_table('academic','student_generations','student generations exist');
select has_table('academic','student_records','student records exist');
select has_table('academic','enrollment_requests','enrollment requests exist');
select has_table('academic','period_enrollments','period enrollments exist');
select has_table('academic','student_group_assignments','group assignments exist');
select has_table('academic','student_offering_enrollments','offering enrollments exist');
select has_table('academic','academic_progress_decisions','progress decisions exist');
select has_table('academic','student_status_history','student status history exists');
select has_table('academic','enrollment_commands','enrollment commands exist');
select has_table('academic','student_academic_events','student academic events exist');

select is((select count(*)::integer from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='academic' and c.relname in ('student_generations','student_records','enrollment_requests','period_enrollments','student_group_assignments','student_offering_enrollments','academic_progress_decisions','student_status_history','enrollment_commands','student_academic_events') and c.relrowsecurity),10,'RLS enabled on all ten tables');
select is((select count(*)::integer from pg_policies where schemaname='academic' and tablename in ('student_generations','student_records','enrollment_requests','period_enrollments','student_group_assignments','student_offering_enrollments','academic_progress_decisions','student_status_history','enrollment_commands','student_academic_events')),0,'new tables have zero policies');
select is((select count(*)::integer from information_schema.role_table_grants where table_schema='academic' and table_name in ('student_generations','student_records','enrollment_requests','period_enrollments','student_group_assignments','student_offering_enrollments','academic_progress_decisions','student_status_history','enrollment_commands','student_academic_events') and grantee in ('PUBLIC','anon','authenticated')),0,'application roles have zero grants');
select is((select count(*)::integer from information_schema.role_usage_grants where object_schema='academic' and grantee in ('PUBLIC','anon','authenticated')),0,'application roles have zero schema usage');
select ok(coalesce(position('academic' in current_setting('pgrst.db_schemas',true)),0)=0,'academic remains outside Data API');
select is((select count(*)::integer from pg_constraint where conrelid='academic.enrollment_commands'::regclass and pg_get_constraintdef(oid) like '%[0-9a-f]{64}%'),1,'commands require SHA-256');
select is((select count(*)::integer from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='academic' and p.proname like '%enrollment%' and pg_get_functiondef(p.oid)~* '\mmd5\M'),0,'enrollment functions contain no MD5');
select is((select count(*)::integer from pg_constraint where connamespace='academic'::regnamespace and contype='f' and conrelid in (select oid from pg_class where relnamespace='academic'::regnamespace and relname in ('student_generations','student_records','enrollment_requests','period_enrollments','student_group_assignments','student_offering_enrollments','academic_progress_decisions','student_status_history','enrollment_commands','student_academic_events')) and confdeltype<>'r'),0,'all new foreign keys restrict deletion');
select is((select count(*)::integer from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname like '%enrollment%'),0,'no enrollment functions in public');
select is((select count(*)::integer from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='auth' and not t.tgisinternal and t.tgname like '%student%'),0,'no Auth triggers added');
select is((select count(*)::integer from pg_trigger where tgfoid='academic.guard_student_academic_history()'::regprocedure and not tgisinternal),10,'all new tables have history guards');
select is((select count(*)::integer from pg_trigger where tgrelid='academic.student_academic_events'::regclass and tgfoid='academic.guard_student_academic_history()'::regprocedure and not tgisinternal),1,'events are append-only');
select is((select count(*)::integer from pg_trigger where tgrelid='academic.enrollment_commands'::regclass and tgfoid='academic.guard_student_academic_history()'::regprocedure and not tgisinternal),1,'completed commands are guarded');
select is((select count(*)::integer from pg_indexes where schemaname='academic' and indexname='one_active_student_record_per_person'),1,'one active record index exists');
select is((select count(*)::integer from pg_indexes where schemaname='academic' and indexname='one_operational_enrollment_per_period'),1,'one operational enrollment index exists');
select is((select count(*)::integer from pg_indexes where schemaname='academic' and indexname='one_active_group_assignment'),1,'one active group assignment index exists');
select is((select count(*)::integer from pg_indexes where schemaname='academic' and indexname='one_confirmed_progress_decision'),1,'one confirmed decision index exists');

select ok(academic.valid_student_record_transition('DRAFT','ACTIVE'),'record draft may activate');
select ok(not academic.valid_student_record_transition('GRADUATED','ACTIVE'),'graduated record cannot reactivate');
select ok(academic.valid_enrollment_request_transition('DRAFT','SUBMITTED'),'request may submit');
select ok(not academic.valid_enrollment_request_transition('REJECTED','APPROVED'),'rejected request cannot approve');
select ok(academic.valid_period_enrollment_transition('PLANNED','ACTIVE'),'enrollment may activate');
select ok(not academic.valid_period_enrollment_transition('COMPLETED','ACTIVE'),'completed enrollment cannot reactivate');
select ok(academic.valid_progress_decision_transition('DRAFT','CONFIRMED'),'decision may confirm');
select ok(not academic.valid_progress_decision_transition('REVERSED','CONFIRMED'),'reversed decision cannot confirm');

select is((select string_agg(enumlabel,',' order by enumsortorder) from pg_enum where enumtypid='academic.student_record_status'::regtype),'DRAFT,ACTIVE,TEMPORARILY_WITHDRAWN,ACADEMICALLY_BLOCKED,COMPLETED,GRADUATED,PERMANENTLY_WITHDRAWN,CANCELLED','student record statuses exact');
select is((select string_agg(enumlabel,',' order by enumsortorder) from pg_enum where enumtypid='academic.student_generation_status'::regtype),'DRAFT,ACTIVE,CLOSED,CANCELLED','generation statuses exact');
select is((select string_agg(enumlabel,',' order by enumsortorder) from pg_enum where enumtypid='academic.enrollment_request_type'::regtype),'INITIAL_ENROLLMENT,REENROLLMENT,REPEAT_SEMESTER,REENTRY_AFTER_TEMPORARY_WITHDRAWAL','request types exact');
select is((select string_agg(enumlabel,',' order by enumsortorder) from pg_enum where enumtypid='academic.enrollment_request_status'::regtype),'DRAFT,SUBMITTED,UNDER_REVIEW,APPROVED,REJECTED,ENROLLED,CANCELLED,EXPIRED','request statuses exact');
select is((select string_agg(enumlabel,',' order by enumsortorder) from pg_enum where enumtypid='academic.enrollment_eligibility_status'::regtype),'PENDING_EVALUATION,ELIGIBLE,ELIGIBLE_WITH_CONDITIONS,NOT_ELIGIBLE,MANUAL_REVIEW_REQUIRED','eligibility statuses exact');
select is((select string_agg(enumlabel,',' order by enumsortorder) from pg_enum where enumtypid='academic.progress_decision_type'::regtype),'ADVANCE,REPEAT,HOLD,TEMPORARY_WITHDRAWAL,PERMANENT_WITHDRAWAL,COMPLETE_STUDIES','decision types exact');
select is((select string_agg(enumlabel,',' order by enumsortorder) from pg_enum where enumtypid='academic.period_enrollment_status'::regtype),'PLANNED,ACTIVE,TEMPORARILY_SUSPENDED,COMPLETED,CANCELLED,WITHDRAWN','enrollment statuses exact');
select is((select string_agg(enumlabel,',' order by enumsortorder) from pg_enum where enumtypid='academic.student_group_assignment_type'::regtype),'INITIAL,ADMINISTRATIVE_CHANGE,CORRECTIVE_CHANGE','assignment types exact');

select has_function('academic','create_student_generation','create generation exists');
select has_function('academic','activate_student_generation','activate generation exists');
select has_function('academic','close_student_generation','close generation exists');
select has_function('academic','create_student_record','create record exists');
select has_function('academic','activate_student_record','activate record exists');
select has_function('academic','create_enrollment_request','create request exists');
select has_function('academic','submit_enrollment_request','submit request exists');
select has_function('academic','begin_enrollment_review','begin review exists');
select has_function('academic','approve_enrollment_request','approve request exists');
select has_function('academic','reject_enrollment_request','reject request exists');
select has_function('academic','cancel_enrollment_request','cancel request exists');
select has_function('academic','expire_enrollment_request','expire request exists');
select has_function('academic','create_progress_decision','create decision exists');
select has_function('academic','confirm_progress_decision','confirm decision exists');
select has_function('academic','reverse_progress_decision','reverse decision exists');
select has_function('academic','create_period_enrollment','create enrollment exists');
select has_function('academic','activate_period_enrollment','activate enrollment exists');
select has_function('academic','complete_period_enrollment','complete enrollment exists');
select has_function('academic','cancel_period_enrollment','cancel enrollment exists');
select has_function('academic','withdraw_period_enrollment','withdraw enrollment exists');
select has_function('academic','assign_student_group','assign group exists');
select has_function('academic','change_student_group','change group exists');
select has_function('academic','end_student_group_assignment','end assignment exists');
select has_function('academic','enroll_student_in_group_offerings','enroll offerings exists');
select has_function('academic','apply_temporary_withdrawal','temporary withdrawal exists');
select has_function('academic','reactivate_student_record','reactivation exists');
select has_function('academic','apply_academic_hold','hold exists');
select has_function('academic','release_academic_hold','release hold exists');
select has_function('academic','apply_permanent_withdrawal','permanent withdrawal exists');
select has_function('academic','complete_student_studies','complete studies exists');
select has_function('academic','validate_group_curriculum_coverage','coverage function exists');

select is((select count(*)::integer from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='academic' and p.proname in ('create_student_generation','activate_student_generation','close_student_generation','create_student_record','activate_student_record','create_enrollment_request','submit_enrollment_request','begin_enrollment_review','approve_enrollment_request','reject_enrollment_request','cancel_enrollment_request','expire_enrollment_request','create_progress_decision','confirm_progress_decision','reverse_progress_decision','create_period_enrollment','activate_period_enrollment','complete_period_enrollment','cancel_period_enrollment','withdraw_period_enrollment','assign_student_group','change_student_group','end_student_group_assignment','enroll_student_in_group_offerings','apply_temporary_withdrawal','reactivate_student_record','apply_academic_hold','release_academic_hold','apply_permanent_withdrawal','complete_student_studies','validate_group_curriculum_coverage') and not(coalesce(p.proconfig,array[]::text[])@>array['search_path=""'])),0,'all operation functions fix search_path');
select is((select count(*)::integer from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='academic' and p.proname like '%student%' and (has_function_privilege('anon',p.oid,'execute') or has_function_privilege('authenticated',p.oid,'execute'))),0,'new functions have no application execute grants');
select ok(academic.academic_request_fingerprint('{"b":2,"a":1}'::jsonb)~'^[0-9a-f]{64}$' and academic.academic_request_fingerprint('{"a":1,"b":2}'::jsonb)=academic.academic_request_fingerprint('{"b":2,"a":1}'::jsonb) and academic.academic_request_fingerprint('{"a":1}'::jsonb)<>academic.academic_request_fingerprint('{"a":2}'::jsonb),'SHA-256 is canonical and discriminating');

select * from finish();
rollback;
