packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  sharp: false
  unrs-resolver: false

catalog:
  supabase: 2.109.1

catalogMode: strict

engineStrict: true

linkWorkspacePackages: false

minimumReleaseAgeExclude:
  - "@supabase/auth-js@2.110.6"
  - "@supabase/functions-js@2.110.6"
  - "@supabase/postgrest-js@2.110.6"
  - "@supabase/realtime-js@2.110.6"
  - "@supabase/storage-js@2.110.6"
  - "@supabase/supabase-js@2.110.6"

saveExact: true

sharedWorkspaceLockfile: true
