packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  sharp: false
  unrs-resolver: false

catalogMode: strict

engineStrict: true

linkWorkspacePackages: false

saveExact: true

sharedWorkspaceLockfile: true
