import { isRole, roles, type Role } from "./roles.js";
import type { RolePermissionMap } from "./types.js";

export const permissions = Object.freeze({
  ACADEMICS_MANAGE: "academics.manage",
  ACADEMICS_READ: "academics.read",
  ACADEMIC_ASSIGNMENTS_MANAGE: "academic.assignments.manage",
  ACADEMIC_ASSIGNMENTS_READ: "academic.assignments.read",
  ACADEMIC_CYCLES_MANAGE: "academic.cycles.manage",
  ACADEMIC_CYCLES_READ: "academic.cycles.read",
  ACADEMIC_GROUPS_MANAGE: "academic.groups.manage",
  ACADEMIC_GROUPS_READ: "academic.groups.read",
  ACADEMIC_OFFERINGS_MANAGE: "academic.offerings.manage",
  ACADEMIC_OFFERINGS_READ: "academic.offerings.read",
  ACADEMIC_PERIODS_MANAGE: "academic.periods.manage",
  ACADEMIC_PERIODS_READ: "academic.periods.read",
  ACADEMIC_PLANS_APPROVE: "academic.plans.approve",
  ACADEMIC_PLANS_MANAGE: "academic.plans.manage",
  ACADEMIC_PLANS_READ: "academic.plans.read",
  ACADEMIC_SUBJECTS_MANAGE: "academic.subjects.manage",
  ACADEMIC_SUBJECTS_READ: "academic.subjects.read",
  ACADEMIC_STUDENTS_READ: "academic.students.read",
  ACADEMIC_STUDENTS_MANAGE: "academic.students.manage",
  ACADEMIC_GENERATIONS_READ: "academic.generations.read",
  ACADEMIC_GENERATIONS_MANAGE: "academic.generations.manage",
  ACADEMIC_ENROLLMENT_REQUESTS_READ: "academic.enrollment_requests.read",
  ACADEMIC_ENROLLMENT_REQUESTS_MANAGE: "academic.enrollment_requests.manage",
  ACADEMIC_ENROLLMENTS_READ: "academic.enrollments.read",
  ACADEMIC_ENROLLMENTS_MANAGE: "academic.enrollments.manage",
  ACADEMIC_GROUP_ASSIGNMENTS_READ: "academic.group_assignments.read",
  ACADEMIC_GROUP_ASSIGNMENTS_MANAGE: "academic.group_assignments.manage",
  ACADEMIC_PROGRESS_READ: "academic.progress.read",
  ACADEMIC_PROGRESS_MANAGE: "academic.progress.manage",
  ACADEMIC_WITHDRAWALS_MANAGE: "academic.withdrawals.manage",
  ACADEMIC_SHIFTS_READ: "academic.shifts.read",
  ACADEMIC_SHIFTS_MANAGE: "academic.shifts.manage",
  ACADEMIC_SPACES_READ: "academic.spaces.read",
  ACADEMIC_SPACES_MANAGE: "academic.spaces.manage",
  ACADEMIC_TIME_BLOCKS_READ: "academic.time_blocks.read",
  ACADEMIC_TIME_BLOCKS_MANAGE: "academic.time_blocks.manage",
  ACADEMIC_SCHEDULE_TEMPLATES_READ: "academic.schedule_templates.read",
  ACADEMIC_SCHEDULE_TEMPLATES_MANAGE: "academic.schedule_templates.manage",
  ACADEMIC_SCHEDULES_READ: "academic.schedules.read",
  ACADEMIC_SCHEDULES_MANAGE: "academic.schedules.manage",
  ACADEMIC_SCHEDULES_APPROVE: "academic.schedules.approve",
  ACADEMIC_SCHEDULES_PUBLISH: "academic.schedules.publish",
  ACADEMIC_TEACHER_AVAILABILITY_READ: "academic.teacher_availability.read",
  ACADEMIC_TEACHER_AVAILABILITY_MANAGE: "academic.teacher_availability.manage",
  ACADEMIC_WORKLOAD_READ: "academic.workload.read",
  ACADEMIC_SCHEDULE_CHANGES_MANAGE: "academic.schedule_changes.manage",
  ACADEMIC_SCHEDULE_CHANGES_APPROVE: "academic.schedule_changes.approve",
  ACADEMIC_ATTENDANCE_READ: "academic.attendance.read",
  ACADEMIC_ATTENDANCE_MANAGE: "academic.attendance.manage",
  ACADEMIC_ATTENDANCE_VALIDATE: "academic.attendance.validate",
  ACADEMIC_PERMISSIONS_READ: "academic.permissions.read",
  ACADEMIC_PERMISSIONS_MANAGE: "academic.permissions.manage",
  ACADEMIC_PERMISSIONS_VALIDATE: "academic.permissions.validate",
  ACADEMIC_LATENESS_READ: "academic.lateness.read",
  ACADEMIC_LATENESS_VALIDATE: "academic.lateness.validate",
  ACADEMIC_LATENESS_NOTIFICATIONS_RECORD: "academic.lateness.notifications.record",
  ACADEMIC_GRADES_READ: "academic.grades.read",
  ACADEMIC_GRADES_CAPTURE: "academic.grades.capture",
  ACADEMIC_GRADES_REVIEW: "academic.grades.review",
  ACADEMIC_GRADES_FINALIZE: "academic.grades.finalize",
  ACADEMIC_GRADES_CORRECT: "academic.grades.correct",
  ACADEMIC_GRADE_WINDOWS_MANAGE: "academic.grade_windows.manage",
  ACADEMIC_SUBJECT_RESULTS_READ: "academic.subject_results.read",
  ACADEMIC_SUBJECT_RESULTS_CALCULATE: "academic.subject_results.calculate",
  ACADEMIC_SUBJECT_RESULTS_CONFIRM: "academic.subject_results.confirm",
  ACADEMIC_SEMESTER_EVALUATIONS_READ: "academic.semester_evaluations.read",
  ACADEMIC_SEMESTER_EVALUATIONS_CALCULATE: "academic.semester_evaluations.calculate",
  ACADEMIC_PROGRESS_DECISIONS_CONFIRM: "academic.progress_decisions.confirm",
  ADMISSIONS_MANAGE: "admissions.manage",
  ADMISSIONS_READ: "admissions.read",
  ATTENDANCE_MANAGE: "attendance.manage",
  ATTENDANCE_READ: "attendance.read",
  AUDIT_READ: "audit.read",
  DOCUMENTS_MANAGE: "documents.manage",
  DOCUMENTS_READ: "documents.read",
  GRADES_MANAGE: "grades.manage",
  GRADES_READ: "grades.read",
  IDENTITY_MANAGE: "identity.manage",
  IDENTITY_READ: "identity.read",
  PAYMENTS_MANAGE: "payments.manage",
  PAYMENTS_READ: "payments.read",
  PORTAL_GUARDIAN_LINKS_APPROVE: "portal.guardian_links.approve",
  PORTAL_GUARDIAN_LINKS_MANAGE: "portal.guardian_links.manage",
  PORTAL_GUARDIAN_LINKS_READ: "portal.guardian_links.read",
  PORTAL_GUARDIAN_LINKS_REVIEW: "portal.guardian_links.review",
  PORTAL_GUARDIAN_LINKS_REVOKE: "portal.guardian_links.revoke",
  PORTAL_GUARDIAN_READ_LINKED_STUDENT_ATTENDANCE: "portal.guardian.read_linked_student_attendance",
  PORTAL_GUARDIAN_READ_LINKED_STUDENT_GRADES: "portal.guardian.read_linked_student_grades",
  PORTAL_GUARDIAN_READ_LINKED_STUDENT_HISTORY: "portal.guardian.read_linked_student_history",
  PORTAL_GUARDIAN_READ_LINKED_STUDENT_OVERVIEW: "portal.guardian.read_linked_student_overview",
  PORTAL_GUARDIAN_READ_LINKED_STUDENT_PERMISSIONS:
    "portal.guardian.read_linked_student_permissions",
  PORTAL_GUARDIAN_READ_LINKED_STUDENT_RECORD: "portal.guardian.read_linked_student_record",
  PORTAL_GUARDIAN_READ_LINKED_STUDENT_SCHEDULE: "portal.guardian.read_linked_student_schedule",
  PORTAL_GUARDIAN_READ_OWN_LINKS: "portal.guardian.read_own_links",
  PORTAL_GUARDIAN_SCOPES_MANAGE: "portal.guardian_scopes.manage",
  REPORTS_EXPORT: "reports.export",
  REPORTS_READ: "reports.read",
  ROLES_ASSIGN: "roles.assign",
  ROLES_READ: "roles.read",
  SETTINGS_MANAGE: "settings.manage",
  SETTINGS_READ: "settings.read",
} as const);

export type Permission = (typeof permissions)[keyof typeof permissions];

export const permissionValues = Object.freeze(Object.values(permissions)) as readonly Permission[];

export function isPermission(value: unknown): value is Permission {
  return typeof value === "string" && permissionValues.some((permission) => permission === value);
}

function permissionSet(...values: Permission[]): readonly Permission[] {
  return Object.freeze(values);
}

export const rolePermissionMap = Object.freeze({
  [roles.SUPERADMIN]: permissionSet(
    permissions.IDENTITY_READ,
    permissions.IDENTITY_MANAGE,
    permissions.ROLES_READ,
    permissions.ROLES_ASSIGN,
    permissions.ADMISSIONS_READ,
    permissions.ADMISSIONS_MANAGE,
    permissions.ACADEMICS_READ,
    permissions.ACADEMICS_MANAGE,
    permissions.ACADEMIC_CYCLES_READ,
    permissions.ACADEMIC_CYCLES_MANAGE,
    permissions.ACADEMIC_PERIODS_READ,
    permissions.ACADEMIC_PERIODS_MANAGE,
    permissions.ACADEMIC_PLANS_READ,
    permissions.ACADEMIC_PLANS_MANAGE,
    permissions.ACADEMIC_PLANS_APPROVE,
    permissions.ACADEMIC_SUBJECTS_READ,
    permissions.ACADEMIC_SUBJECTS_MANAGE,
    permissions.ACADEMIC_GROUPS_READ,
    permissions.ACADEMIC_GROUPS_MANAGE,
    permissions.ACADEMIC_OFFERINGS_READ,
    permissions.ACADEMIC_OFFERINGS_MANAGE,
    permissions.ACADEMIC_ASSIGNMENTS_READ,
    permissions.ACADEMIC_ASSIGNMENTS_MANAGE,
    permissions.ACADEMIC_STUDENTS_READ,
    permissions.ACADEMIC_STUDENTS_MANAGE,
    permissions.ACADEMIC_GENERATIONS_READ,
    permissions.ACADEMIC_GENERATIONS_MANAGE,
    permissions.ACADEMIC_ENROLLMENT_REQUESTS_READ,
    permissions.ACADEMIC_ENROLLMENT_REQUESTS_MANAGE,
    permissions.ACADEMIC_ENROLLMENTS_READ,
    permissions.ACADEMIC_ENROLLMENTS_MANAGE,
    permissions.ACADEMIC_GROUP_ASSIGNMENTS_READ,
    permissions.ACADEMIC_GROUP_ASSIGNMENTS_MANAGE,
    permissions.ACADEMIC_PROGRESS_READ,
    permissions.ACADEMIC_PROGRESS_MANAGE,
    permissions.ACADEMIC_WITHDRAWALS_MANAGE,
    permissions.ACADEMIC_SHIFTS_READ,
    permissions.ACADEMIC_SHIFTS_MANAGE,
    permissions.ACADEMIC_SPACES_READ,
    permissions.ACADEMIC_SPACES_MANAGE,
    permissions.ACADEMIC_TIME_BLOCKS_READ,
    permissions.ACADEMIC_TIME_BLOCKS_MANAGE,
    permissions.ACADEMIC_SCHEDULE_TEMPLATES_READ,
    permissions.ACADEMIC_SCHEDULE_TEMPLATES_MANAGE,
    permissions.ACADEMIC_SCHEDULES_READ,
    permissions.ACADEMIC_SCHEDULES_MANAGE,
    permissions.ACADEMIC_SCHEDULES_APPROVE,
    permissions.ACADEMIC_SCHEDULES_PUBLISH,
    permissions.ACADEMIC_TEACHER_AVAILABILITY_READ,
    permissions.ACADEMIC_TEACHER_AVAILABILITY_MANAGE,
    permissions.ACADEMIC_WORKLOAD_READ,
    permissions.ACADEMIC_SCHEDULE_CHANGES_MANAGE,
    permissions.ACADEMIC_SCHEDULE_CHANGES_APPROVE,
    permissions.ACADEMIC_ATTENDANCE_READ,
    permissions.ACADEMIC_ATTENDANCE_MANAGE,
    permissions.ACADEMIC_ATTENDANCE_VALIDATE,
    permissions.ACADEMIC_PERMISSIONS_READ,
    permissions.ACADEMIC_PERMISSIONS_MANAGE,
    permissions.ACADEMIC_PERMISSIONS_VALIDATE,
    permissions.ACADEMIC_LATENESS_READ,
    permissions.ACADEMIC_LATENESS_VALIDATE,
    permissions.ACADEMIC_LATENESS_NOTIFICATIONS_RECORD,
    permissions.ACADEMIC_GRADES_READ,
    permissions.ACADEMIC_GRADES_CAPTURE,
    permissions.ACADEMIC_GRADES_REVIEW,
    permissions.ACADEMIC_GRADES_FINALIZE,
    permissions.ACADEMIC_GRADES_CORRECT,
    permissions.ACADEMIC_GRADE_WINDOWS_MANAGE,
    permissions.ACADEMIC_SUBJECT_RESULTS_READ,
    permissions.ACADEMIC_SUBJECT_RESULTS_CALCULATE,
    permissions.ACADEMIC_SUBJECT_RESULTS_CONFIRM,
    permissions.ACADEMIC_SEMESTER_EVALUATIONS_READ,
    permissions.ACADEMIC_SEMESTER_EVALUATIONS_CALCULATE,
    permissions.ACADEMIC_PROGRESS_DECISIONS_CONFIRM,
    permissions.ATTENDANCE_READ,
    permissions.ATTENDANCE_MANAGE,
    permissions.GRADES_READ,
    permissions.GRADES_MANAGE,
    permissions.PAYMENTS_READ,
    permissions.PAYMENTS_MANAGE,
    permissions.PORTAL_GUARDIAN_READ_OWN_LINKS,
    permissions.PORTAL_GUARDIAN_READ_LINKED_STUDENT_OVERVIEW,
    permissions.PORTAL_GUARDIAN_READ_LINKED_STUDENT_RECORD,
    permissions.PORTAL_GUARDIAN_READ_LINKED_STUDENT_SCHEDULE,
    permissions.PORTAL_GUARDIAN_READ_LINKED_STUDENT_ATTENDANCE,
    permissions.PORTAL_GUARDIAN_READ_LINKED_STUDENT_PERMISSIONS,
    permissions.PORTAL_GUARDIAN_READ_LINKED_STUDENT_GRADES,
    permissions.PORTAL_GUARDIAN_READ_LINKED_STUDENT_HISTORY,
    permissions.PORTAL_GUARDIAN_LINKS_READ,
    permissions.PORTAL_GUARDIAN_LINKS_MANAGE,
    permissions.PORTAL_GUARDIAN_LINKS_REVIEW,
    permissions.PORTAL_GUARDIAN_LINKS_APPROVE,
    permissions.PORTAL_GUARDIAN_LINKS_REVOKE,
    permissions.PORTAL_GUARDIAN_SCOPES_MANAGE,
    permissions.DOCUMENTS_READ,
    permissions.DOCUMENTS_MANAGE,
    permissions.REPORTS_READ,
    permissions.REPORTS_EXPORT,
    permissions.SETTINGS_READ,
    permissions.SETTINGS_MANAGE,
    permissions.AUDIT_READ,
  ),
  [roles.ADMINISTRATIVO]: permissionSet(
    permissions.IDENTITY_READ,
    permissions.ROLES_READ,
    permissions.ADMISSIONS_READ,
    permissions.ADMISSIONS_MANAGE,
    permissions.ACADEMICS_READ,
    permissions.ACADEMIC_CYCLES_READ,
    permissions.ACADEMIC_CYCLES_MANAGE,
    permissions.ACADEMIC_PERIODS_READ,
    permissions.ACADEMIC_PERIODS_MANAGE,
    permissions.ACADEMIC_PLANS_READ,
    permissions.ACADEMIC_PLANS_MANAGE,
    permissions.ACADEMIC_PLANS_APPROVE,
    permissions.ACADEMIC_SUBJECTS_READ,
    permissions.ACADEMIC_SUBJECTS_MANAGE,
    permissions.ACADEMIC_GROUPS_READ,
    permissions.ACADEMIC_GROUPS_MANAGE,
    permissions.ACADEMIC_OFFERINGS_READ,
    permissions.ACADEMIC_OFFERINGS_MANAGE,
    permissions.ACADEMIC_ASSIGNMENTS_READ,
    permissions.ACADEMIC_ASSIGNMENTS_MANAGE,
    permissions.ACADEMIC_STUDENTS_READ,
    permissions.ACADEMIC_STUDENTS_MANAGE,
    permissions.ACADEMIC_GENERATIONS_READ,
    permissions.ACADEMIC_GENERATIONS_MANAGE,
    permissions.ACADEMIC_ENROLLMENT_REQUESTS_READ,
    permissions.ACADEMIC_ENROLLMENT_REQUESTS_MANAGE,
    permissions.ACADEMIC_ENROLLMENTS_READ,
    permissions.ACADEMIC_ENROLLMENTS_MANAGE,
    permissions.ACADEMIC_GROUP_ASSIGNMENTS_READ,
    permissions.ACADEMIC_GROUP_ASSIGNMENTS_MANAGE,
    permissions.ACADEMIC_PROGRESS_READ,
    permissions.ACADEMIC_PROGRESS_MANAGE,
    permissions.ACADEMIC_WITHDRAWALS_MANAGE,
    permissions.ACADEMIC_SHIFTS_READ,
    permissions.ACADEMIC_SHIFTS_MANAGE,
    permissions.ACADEMIC_SPACES_READ,
    permissions.ACADEMIC_SPACES_MANAGE,
    permissions.ACADEMIC_TIME_BLOCKS_READ,
    permissions.ACADEMIC_TIME_BLOCKS_MANAGE,
    permissions.ACADEMIC_SCHEDULE_TEMPLATES_READ,
    permissions.ACADEMIC_SCHEDULE_TEMPLATES_MANAGE,
    permissions.ACADEMIC_SCHEDULES_READ,
    permissions.ACADEMIC_SCHEDULES_MANAGE,
    permissions.ACADEMIC_SCHEDULES_APPROVE,
    permissions.ACADEMIC_SCHEDULES_PUBLISH,
    permissions.ACADEMIC_TEACHER_AVAILABILITY_READ,
    permissions.ACADEMIC_TEACHER_AVAILABILITY_MANAGE,
    permissions.ACADEMIC_WORKLOAD_READ,
    permissions.ACADEMIC_SCHEDULE_CHANGES_MANAGE,
    permissions.ACADEMIC_SCHEDULE_CHANGES_APPROVE,
    permissions.ACADEMIC_ATTENDANCE_READ,
    permissions.ACADEMIC_ATTENDANCE_MANAGE,
    permissions.ACADEMIC_PERMISSIONS_READ,
    permissions.ACADEMIC_PERMISSIONS_MANAGE,
    permissions.ACADEMIC_LATENESS_READ,
    permissions.ACADEMIC_GRADES_READ,
    permissions.ACADEMIC_GRADES_REVIEW,
    permissions.ACADEMIC_GRADES_CORRECT,
    permissions.ACADEMIC_GRADE_WINDOWS_MANAGE,
    permissions.ACADEMIC_SUBJECT_RESULTS_READ,
    permissions.ACADEMIC_SUBJECT_RESULTS_CONFIRM,
    permissions.ACADEMIC_SEMESTER_EVALUATIONS_READ,
    permissions.ACADEMIC_PROGRESS_DECISIONS_CONFIRM,
    permissions.PAYMENTS_READ,
    permissions.PORTAL_GUARDIAN_LINKS_READ,
    permissions.PORTAL_GUARDIAN_LINKS_MANAGE,
    permissions.PORTAL_GUARDIAN_LINKS_REVIEW,
    permissions.PORTAL_GUARDIAN_LINKS_APPROVE,
    permissions.PORTAL_GUARDIAN_LINKS_REVOKE,
    permissions.DOCUMENTS_READ,
    permissions.DOCUMENTS_MANAGE,
    permissions.REPORTS_READ,
    permissions.REPORTS_EXPORT,
    permissions.SETTINGS_READ,
  ),
  [roles.CONTROL_ESCOLAR]: permissionSet(
    permissions.IDENTITY_READ,
    permissions.ADMISSIONS_READ,
    permissions.ADMISSIONS_MANAGE,
    permissions.ACADEMICS_READ,
    permissions.ACADEMICS_MANAGE,
    permissions.ACADEMIC_CYCLES_READ,
    permissions.ACADEMIC_PERIODS_READ,
    permissions.ACADEMIC_PLANS_READ,
    permissions.ACADEMIC_SUBJECTS_READ,
    permissions.ACADEMIC_GROUPS_READ,
    permissions.ACADEMIC_GROUPS_MANAGE,
    permissions.ACADEMIC_OFFERINGS_READ,
    permissions.ACADEMIC_OFFERINGS_MANAGE,
    permissions.ACADEMIC_ASSIGNMENTS_READ,
    permissions.ACADEMIC_ASSIGNMENTS_MANAGE,
    permissions.ACADEMIC_STUDENTS_READ,
    permissions.ACADEMIC_STUDENTS_MANAGE,
    permissions.ACADEMIC_GENERATIONS_READ,
    permissions.ACADEMIC_GENERATIONS_MANAGE,
    permissions.ACADEMIC_ENROLLMENT_REQUESTS_READ,
    permissions.ACADEMIC_ENROLLMENT_REQUESTS_MANAGE,
    permissions.ACADEMIC_ENROLLMENTS_READ,
    permissions.ACADEMIC_ENROLLMENTS_MANAGE,
    permissions.ACADEMIC_GROUP_ASSIGNMENTS_READ,
    permissions.ACADEMIC_GROUP_ASSIGNMENTS_MANAGE,
    permissions.ACADEMIC_PROGRESS_READ,
    permissions.ACADEMIC_PROGRESS_MANAGE,
    permissions.ACADEMIC_SCHEDULES_READ,
    permissions.ACADEMIC_SCHEDULES_MANAGE,
    permissions.ACADEMIC_SCHEDULES_APPROVE,
    permissions.ACADEMIC_SCHEDULES_PUBLISH,
    permissions.ACADEMIC_TEACHER_AVAILABILITY_READ,
    permissions.ACADEMIC_TEACHER_AVAILABILITY_MANAGE,
    permissions.ACADEMIC_WORKLOAD_READ,
    permissions.ACADEMIC_SCHEDULE_CHANGES_MANAGE,
    permissions.ACADEMIC_SCHEDULE_CHANGES_APPROVE,
    permissions.ACADEMIC_ATTENDANCE_READ,
    permissions.ACADEMIC_ATTENDANCE_MANAGE,
    permissions.ACADEMIC_PERMISSIONS_READ,
    permissions.ACADEMIC_PERMISSIONS_MANAGE,
    permissions.ACADEMIC_LATENESS_READ,
    permissions.ACADEMIC_GRADES_READ,
    permissions.ACADEMIC_GRADES_REVIEW,
    permissions.ACADEMIC_GRADES_CORRECT,
    permissions.ACADEMIC_GRADE_WINDOWS_MANAGE,
    permissions.ACADEMIC_SUBJECT_RESULTS_READ,
    permissions.ACADEMIC_SUBJECT_RESULTS_CALCULATE,
    permissions.ACADEMIC_SUBJECT_RESULTS_CONFIRM,
    permissions.ACADEMIC_SEMESTER_EVALUATIONS_READ,
    permissions.ACADEMIC_SEMESTER_EVALUATIONS_CALCULATE,
    permissions.ACADEMIC_PROGRESS_DECISIONS_CONFIRM,
    permissions.ATTENDANCE_READ,
    permissions.ATTENDANCE_MANAGE,
    permissions.GRADES_READ,
    permissions.GRADES_MANAGE,
    permissions.PORTAL_GUARDIAN_LINKS_READ,
    permissions.PORTAL_GUARDIAN_LINKS_MANAGE,
    permissions.PORTAL_GUARDIAN_LINKS_REVIEW,
    permissions.PORTAL_GUARDIAN_LINKS_APPROVE,
    permissions.PORTAL_GUARDIAN_LINKS_REVOKE,
    permissions.DOCUMENTS_READ,
    permissions.DOCUMENTS_MANAGE,
    permissions.REPORTS_READ,
    permissions.REPORTS_EXPORT,
  ),
  [roles.CAJA]: permissionSet(
    permissions.IDENTITY_READ,
    permissions.ADMISSIONS_READ,
    permissions.PAYMENTS_READ,
    permissions.PAYMENTS_MANAGE,
    permissions.REPORTS_READ,
  ),
  [roles.PREFECTURA]: permissionSet(
    permissions.ACADEMICS_READ,
    permissions.ACADEMIC_GROUPS_READ,
    permissions.ACADEMIC_OFFERINGS_READ,
    permissions.ACADEMIC_ASSIGNMENTS_READ,
    permissions.ACADEMIC_SCHEDULES_READ,
    permissions.ACADEMIC_ATTENDANCE_READ,
    permissions.ACADEMIC_ATTENDANCE_MANAGE,
    permissions.ACADEMIC_ATTENDANCE_VALIDATE,
    permissions.ACADEMIC_PERMISSIONS_READ,
    permissions.ACADEMIC_PERMISSIONS_MANAGE,
    permissions.ACADEMIC_PERMISSIONS_VALIDATE,
    permissions.ACADEMIC_LATENESS_READ,
    permissions.ACADEMIC_LATENESS_VALIDATE,
    permissions.ACADEMIC_LATENESS_NOTIFICATIONS_RECORD,
  ),
  [roles.DOCENTE]: permissionSet(
    permissions.ACADEMICS_READ,
    permissions.ATTENDANCE_READ,
    permissions.ATTENDANCE_MANAGE,
    permissions.ACADEMIC_ATTENDANCE_READ,
    permissions.ACADEMIC_ATTENDANCE_MANAGE,
    permissions.ACADEMIC_GRADES_READ,
    permissions.ACADEMIC_GRADES_CAPTURE,
    permissions.ACADEMIC_GRADES_REVIEW,
    permissions.ACADEMIC_GRADES_FINALIZE,
    permissions.ACADEMIC_SUBJECT_RESULTS_READ,
    permissions.GRADES_READ,
    permissions.GRADES_MANAGE,
    permissions.DOCUMENTS_READ,
  ),
  [roles.TUTOR]: permissionSet(
    permissions.ACADEMICS_READ,
    permissions.ATTENDANCE_READ,
    permissions.GRADES_READ,
    permissions.PAYMENTS_READ,
    permissions.PORTAL_GUARDIAN_READ_OWN_LINKS,
    permissions.PORTAL_GUARDIAN_READ_LINKED_STUDENT_OVERVIEW,
    permissions.PORTAL_GUARDIAN_READ_LINKED_STUDENT_RECORD,
    permissions.PORTAL_GUARDIAN_READ_LINKED_STUDENT_SCHEDULE,
    permissions.PORTAL_GUARDIAN_READ_LINKED_STUDENT_ATTENDANCE,
    permissions.PORTAL_GUARDIAN_READ_LINKED_STUDENT_PERMISSIONS,
    permissions.PORTAL_GUARDIAN_READ_LINKED_STUDENT_GRADES,
    permissions.PORTAL_GUARDIAN_READ_LINKED_STUDENT_HISTORY,
    permissions.DOCUMENTS_READ,
  ),
  [roles.ALUMNO]: permissionSet(
    permissions.ACADEMICS_READ,
    permissions.ATTENDANCE_READ,
    permissions.GRADES_READ,
    permissions.PAYMENTS_READ,
    permissions.DOCUMENTS_READ,
  ),
  [roles.ASPIRANTE]: permissionSet(
    permissions.ADMISSIONS_READ,
    permissions.PAYMENTS_READ,
    permissions.DOCUMENTS_READ,
  ),
}) satisfies RolePermissionMap;

const noPermissions = Object.freeze([]) as readonly Permission[];

export function permissionsForRole(role: Role): readonly Permission[];
export function permissionsForRole(role: unknown): readonly Permission[];
export function permissionsForRole(role: unknown): readonly Permission[] {
  if (!isRole(role)) {
    return noPermissions;
  }
  return rolePermissionMap[role];
}
