begin;

create extension if not exists pgcrypto with schema extensions;

create type academic.grade_window_type as enum ('UNIT_CAPTURE','FINAL_REVIEW','CORRECTION');
create type academic.grade_window_status as enum ('DRAFT','OPEN','CLOSED','CANCELLED');
create type academic.unit_grade_status as enum ('DRAFT','CAPTURED','REVIEWED','FINALIZED','CORRECTED','CANCELLED');
create type academic.subject_result_code as enum ('AC','NA','PENDING');
create type academic.grade_calculation_status as enum ('COMPLETE','INCOMPLETE','MANUAL_REVIEW_REQUIRED');
create type academic.subject_result_status as enum ('DRAFT','CALCULATED','CONFIRMED','CORRECTED','CANCELLED');
create type academic.semester_evaluation_status as enum ('INCOMPLETE','COMPLETE','MANUAL_REVIEW_REQUIRED','CONFIRMED');
create type academic.progress_proposal as enum ('ADVANCE','REPEAT','HOLD','COMPLETE_STUDIES','MANUAL_REVIEW_REQUIRED');
create type academic.grade_proposal_reason as enum ('ALL_SUBJECTS_AC','NON_ACCREDITED_SUBJECTS_REQUIRE_POLICY','SUBJECT_RESULTS_PENDING','SIXTH_SEMESTER_REQUIRES_REVIEW','INSTITUTIONAL_REVIEW');
create type academic.grade_correction_status as enum ('DRAFT','SUBMITTED','UNDER_REVIEW','APPROVED','REJECTED','APPLIED','CANCELLED');
create type academic.grade_correction_reason as enum ('DATA_ENTRY_ERROR','INSTITUTIONAL_REVIEW','TEACHER_CORRECTION','CONTROL_ESCOLAR_CORRECTION','AUTHORIZED_LATE_CAPTURE','OTHER_PENDING_VALIDATION');
create type academic.grade_command_status as enum ('IN_PROGRESS','COMPLETED','FAILED');
create type academic.grade_command_type as enum ('CREATE_WINDOW','OPEN_WINDOW','CLOSE_WINDOW','CANCEL_WINDOW','CAPTURE_GRADE','CAPTURE_BULK_GRADES','REVIEW_GRADE','FINALIZE_GRADE','CANCEL_GRADE','CALCULATE_SUBJECT_RESULT','CONFIRM_SUBJECT_RESULT','CALCULATE_SEMESTER','CONFIRM_PROGRESS','CREATE_CORRECTION','SUBMIT_CORRECTION','BEGIN_CORRECTION_REVIEW','APPROVE_CORRECTION','REJECT_CORRECTION','APPLY_CORRECTION','CANCEL_CORRECTION');
create type academic.grade_entity_type as enum ('GRADE_WINDOW','UNIT_GRADE','SUBJECT_RESULT','SEMESTER_SUMMARY','GRADE_CORRECTION','PROGRESS_DECISION');
create type academic.grade_event_type as enum ('GRADE_WINDOW_CREATED','GRADE_WINDOW_OPENED','GRADE_WINDOW_CLOSED','GRADE_WINDOW_CANCELLED','UNIT_GRADE_CAPTURED','BULK_UNIT_GRADES_CAPTURED','UNIT_GRADE_REVIEWED','UNIT_GRADE_FINALIZED','SUBJECT_RESULT_CALCULATED','SUBJECT_RESULT_CONFIRMED','SEMESTER_EVALUATION_CALCULATED','PROGRESS_DECISION_PROPOSED','PROGRESS_DECISION_CONFIRMED','GRADE_CORRECTION_CREATED','GRADE_CORRECTION_APPROVED','GRADE_CORRECTION_APPLIED','SUBJECT_RESULT_RECALCULATED','SEMESTER_EVALUATION_RECALCULATED','OPERATION_REJECTED');

create table academic.grade_capture_windows(
 id uuid primary key default gen_random_uuid(), academic_period_id uuid not null references academic.academic_periods(id) on delete restrict,
 unit_number smallint check(unit_number between 1 and 3), window_type academic.grade_window_type not null, opens_at timestamptz not null, closes_at timestamptz not null,
 status academic.grade_window_status not null default 'DRAFT', created_by_account_id uuid not null references core.accounts(id) on delete restrict,
 opened_by_account_id uuid references core.accounts(id) on delete restrict, closed_by_account_id uuid references core.accounts(id) on delete restrict,
 created_at timestamptz not null default now(), opened_at timestamptz, closed_at timestamptz, updated_at timestamptz not null default now(),
 check(opens_at<closes_at), check((window_type='UNIT_CAPTURE' and unit_number is not null) or (window_type<>'UNIT_CAPTURE' and unit_number is null))
);
create unique index one_operational_grade_window on academic.grade_capture_windows(academic_period_id,window_type,coalesce(unit_number,0)) where status in ('DRAFT','OPEN');

create table academic.student_unit_grades(
 id uuid primary key default gen_random_uuid(), student_record_id uuid not null references academic.student_records(id) on delete restrict,
 period_enrollment_id uuid not null references academic.period_enrollments(id) on delete restrict, student_offering_enrollment_id uuid not null references academic.student_offering_enrollments(id) on delete restrict,
 academic_offering_id uuid not null references academic.academic_offerings(id) on delete restrict, subject_unit_id uuid not null references academic.subject_units(id) on delete restrict,
 unit_number smallint not null check(unit_number between 1 and 3), raw_grade numeric(6,3) not null check(raw_grade between 0 and 10), normalized_grade numeric(6,3) not null check(normalized_grade between 0 and 10),
 is_accredited boolean not null, status academic.unit_grade_status not null default 'CAPTURED', captured_by_account_id uuid not null references core.accounts(id) on delete restrict,
 reviewed_by_account_id uuid references core.accounts(id) on delete restrict, finalized_by_account_id uuid references core.accounts(id) on delete restrict,
 captured_at timestamptz not null default now(), reviewed_at timestamptz, finalized_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 unique(student_offering_enrollment_id,unit_number), unique(student_offering_enrollment_id,subject_unit_id)
);
create table academic.student_unit_grade_history(
 id uuid primary key default gen_random_uuid(), student_unit_grade_id uuid not null references academic.student_unit_grades(id) on delete restrict,
 previous_raw_grade numeric(6,3), resulting_raw_grade numeric(6,3) not null, previous_status academic.unit_grade_status, resulting_status academic.unit_grade_status not null,
 actor_account_id uuid not null references core.accounts(id) on delete restrict, reason_code text not null check(char_length(reason_code) between 1 and 80), correction_id uuid,
 created_at timestamptz not null default now()
);
create table academic.subject_final_results(
 id uuid primary key default gen_random_uuid(), student_record_id uuid not null references academic.student_records(id) on delete restrict,
 period_enrollment_id uuid not null references academic.period_enrollments(id) on delete restrict, student_offering_enrollment_id uuid not null references academic.student_offering_enrollments(id) on delete restrict,
 academic_offering_id uuid not null references academic.academic_offerings(id) on delete restrict, accredited_unit_count smallint not null check(accredited_unit_count between 0 and 3),
 non_accredited_unit_count smallint not null check(non_accredited_unit_count between 0 and 3), raw_final_grade numeric(6,3), rounded_final_grade numeric(6,3),
 result_code academic.subject_result_code not null, calculation_status academic.grade_calculation_status not null, status academic.subject_result_status not null default 'DRAFT',
 calculated_by_account_id uuid not null references core.accounts(id) on delete restrict, confirmed_by_account_id uuid references core.accounts(id) on delete restrict,
 calculated_at timestamptz not null default now(), confirmed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 unique(student_offering_enrollment_id), check(raw_final_grade is null or raw_final_grade between 0 and 10), check(rounded_final_grade is null or rounded_final_grade between 0 and 10)
);
create table academic.subject_result_history(
 id uuid primary key default gen_random_uuid(), subject_final_result_id uuid not null references academic.subject_final_results(id) on delete restrict,
 previous_result academic.subject_result_code, resulting_result academic.subject_result_code not null, previous_status academic.subject_result_status, resulting_status academic.subject_result_status not null,
 actor_account_id uuid not null references core.accounts(id) on delete restrict, created_at timestamptz not null default now()
);
create table academic.semester_evaluation_summaries(
 id uuid primary key default gen_random_uuid(), student_record_id uuid not null references academic.student_records(id) on delete restrict,
 period_enrollment_id uuid not null references academic.period_enrollments(id) on delete restrict, academic_period_id uuid not null references academic.academic_periods(id) on delete restrict,
 semester_number smallint not null check(semester_number between 1 and 6), total_subject_count integer not null check(total_subject_count>=0), accredited_subject_count integer not null check(accredited_subject_count>=0),
 non_accredited_subject_count integer not null check(non_accredited_subject_count>=0), pending_subject_count integer not null check(pending_subject_count>=0),
 evaluation_status academic.semester_evaluation_status not null, proposed_progress_decision academic.progress_proposal not null, proposal_reason_code academic.grade_proposal_reason not null,
 calculated_by_account_id uuid not null references core.accounts(id) on delete restrict, confirmed_by_account_id uuid references core.accounts(id) on delete restrict,
 progress_decision_id uuid references academic.academic_progress_decisions(id) on delete restrict, calculated_at timestamptz not null default now(), confirmed_at timestamptz,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(period_enrollment_id)
);
create table academic.grade_corrections(
 id uuid primary key default gen_random_uuid(), student_unit_grade_id uuid not null references academic.student_unit_grades(id) on delete restrict,
 previous_raw_grade numeric(6,3) not null, proposed_raw_grade numeric(6,3) not null check(proposed_raw_grade between 0 and 10), reason_code academic.grade_correction_reason not null,
 status academic.grade_correction_status not null default 'DRAFT', requested_by_account_id uuid not null references core.accounts(id) on delete restrict,
 reviewed_by_account_id uuid references core.accounts(id) on delete restrict, approved_by_account_id uuid references core.accounts(id) on delete restrict, applied_by_account_id uuid references core.accounts(id) on delete restrict,
 idempotency_key text not null, request_fingerprint text not null check(request_fingerprint~'^[0-9a-f]{64}$'), requested_at timestamptz not null default now(), reviewed_at timestamptz,
 approved_at timestamptz, applied_at timestamptz, rejected_at timestamptz, cancelled_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 unique(requested_by_account_id,idempotency_key)
);
alter table academic.student_unit_grade_history add constraint student_unit_grade_history_correction_fk foreign key(correction_id) references academic.grade_corrections(id) on delete restrict;
create table academic.grade_commands(
 id uuid primary key default gen_random_uuid(), idempotency_key text not null, command_type academic.grade_command_type not null,
 actor_account_id uuid not null references core.accounts(id) on delete restrict, request_fingerprint text not null check(request_fingerprint~'^[0-9a-f]{64}$'),
 resulting_entity_type academic.grade_entity_type, resulting_entity_id uuid, status academic.grade_command_status not null default 'IN_PROGRESS', created_at timestamptz not null default now(), completed_at timestamptz,
 unique(actor_account_id,command_type,idempotency_key), check((status='COMPLETED')=(completed_at is not null))
);
create table academic.grade_events(
 id uuid primary key default gen_random_uuid(), student_record_id uuid references academic.student_records(id) on delete restrict, entity_type academic.grade_entity_type not null, entity_id uuid not null,
 event_type academic.grade_event_type not null, actor_account_id uuid not null references core.accounts(id) on delete restrict, previous_status text, resulting_status text,
 idempotency_key text not null, correlation_id uuid, occurred_at timestamptz not null default now(), unique(actor_account_id,event_type,idempotency_key)
);

create function academic.apply_institutional_grade_rounding(raw_grade numeric) returns numeric language plpgsql immutable strict security invoker set search_path='' as $$
declare n integer;
begin
 if raw_grade<0 or raw_grade>10 then raise exception 'INVALID_GRADE_VALUE'; end if;
 if raw_grade<6 then return raw_grade; end if;
 if raw_grade=10 then return 10; end if;
 n:=floor(raw_grade);
 if raw_grade<=n+0.25 then return n; elsif raw_grade<=n+0.75 then return n+0.5; else return least(n+1,10); end if;
end$$;
create function academic.grade_fingerprint(payload jsonb) returns text language sql immutable strict security invoker set search_path='' as $$select encode(extensions.digest(convert_to(payload::text,'UTF8'),'sha256'),'hex')$$;

create function academic.require_grade_permission(permission_code text) returns uuid language plpgsql volatile security definer set search_path='' as $$
declare actor uuid; account record; allowed boolean;
begin
 actor:=auth.uid(); if actor is null then raise exception 'ACTOR_NOT_AUTHORIZED'; end if;
 select a.* into account from core.accounts a where a.auth_user_id=actor for update;
 if account.id is null or account.account_status<>'ACTIVE' or account.session_version<>coalesce((auth.jwt()->>'session_version')::integer,0) then raise exception 'ACTOR_NOT_AUTHORIZED'; end if;
 if coalesce(auth.jwt()->>'aal','')<>'aal2' then raise exception 'AAL2_REQUIRED'; end if;
 select exists(select 1 from core.account_roles ar join core.roles r on r.id=ar.role_id where ar.account_id=account.id and ar.revoked_at is null and (
  r.code='SUPERADMIN' or
  (permission_code in ('academic.grades.read','academic.grades.review','academic.grades.correct','academic.grade_windows.manage','academic.subject_results.read','academic.subject_results.calculate','academic.subject_results.confirm','academic.semester_evaluations.read','academic.semester_evaluations.calculate','academic.progress_decisions.confirm') and r.code in ('ADMINISTRATIVO','CONTROL_ESCOLAR')) or
  (permission_code in ('academic.grades.read','academic.grades.capture','academic.grades.review','academic.grades.finalize','academic.subject_results.read') and r.code='DOCENTE')
 )) into allowed;
 if not allowed then raise exception 'ACTOR_NOT_AUTHORIZED'; end if; return account.id;
end$$;
create function academic.begin_grade_command(actor uuid,kind academic.grade_command_type,operation_key text,payload jsonb) returns uuid language plpgsql security definer set search_path='' as $$
declare fingerprint text; existing academic.grade_commands%rowtype;
begin fingerprint:=academic.grade_fingerprint(payload); perform pg_advisory_xact_lock(hashtextextended(actor::text||kind::text||operation_key,0)); select * into existing from academic.grade_commands where actor_account_id=actor and command_type=kind and idempotency_key=operation_key for update;
 if existing.id is not null then if existing.request_fingerprint<>fingerprint then raise exception 'IDEMPOTENCY_CONFLICT'; end if; if existing.status='COMPLETED' then return existing.resulting_entity_id; end if; raise exception 'CONCURRENT_MODIFICATION'; end if;
 insert into academic.grade_commands(idempotency_key,command_type,actor_account_id,request_fingerprint) values(operation_key,kind,actor,fingerprint); return null; end$$;
create function academic.complete_grade_command(actor uuid,kind academic.grade_command_type,operation_key text,entity_type academic.grade_entity_type,entity_id uuid) returns void language sql security definer set search_path='' as $$update academic.grade_commands set status='COMPLETED',resulting_entity_type=entity_type,resulting_entity_id=entity_id,completed_at=statement_timestamp() where actor_account_id=actor and command_type=kind and idempotency_key=operation_key$$;
create function academic.append_grade_event(student_id uuid,entity_type academic.grade_entity_type,entity_id uuid,event academic.grade_event_type,actor uuid,old_status text,new_status text,operation_key text,correlation uuid default null) returns void language sql security definer set search_path='' as $$insert into academic.grade_events(student_record_id,entity_type,entity_id,event_type,actor_account_id,previous_status,resulting_status,idempotency_key,correlation_id) values(student_id,entity_type,entity_id,event,actor,old_status,new_status,operation_key,correlation) on conflict do nothing$$;

create function academic.create_grade_capture_window(period_id uuid,unit smallint,kind academic.grade_window_type,opens timestamptz,closes timestamptz,operation_key text,correlation uuid default null) returns table(entity_id uuid,status text) language plpgsql security definer set search_path='' as $$
declare actor uuid; prior uuid; created uuid; begin actor:=academic.require_grade_permission('academic.grade_windows.manage'); prior:=academic.begin_grade_command(actor,'CREATE_WINDOW',operation_key,jsonb_build_object('period',period_id,'unit',unit,'kind',kind,'opens',opens,'closes',closes)); if prior is not null then return query select prior,'DRAFT'; return; end if;
 if opens>=closes or (kind='UNIT_CAPTURE' and unit not between 1 and 3) or (kind<>'UNIT_CAPTURE' and unit is not null) then raise exception 'GRADE_WINDOW_INVALID_STATE'; end if;
 insert into academic.grade_capture_windows(academic_period_id,unit_number,window_type,opens_at,closes_at,created_by_account_id) values(period_id,unit,kind,opens,closes,actor) returning id into created;
 perform academic.complete_grade_command(actor,'CREATE_WINDOW',operation_key,'GRADE_WINDOW',created); perform academic.append_grade_event(null,'GRADE_WINDOW',created,'GRADE_WINDOW_CREATED',actor,null,'DRAFT',operation_key,correlation); return query select created,'DRAFT'; end$$;
create function academic.change_grade_window_status(window_id uuid,target academic.grade_window_status,kind academic.grade_command_type,event academic.grade_event_type,operation_key text,correlation uuid) returns table(entity_id uuid,status text) language plpgsql security definer set search_path='' as $$
declare actor uuid; prior uuid; w academic.grade_capture_windows%rowtype; valid boolean; begin actor:=academic.require_grade_permission('academic.grade_windows.manage'); prior:=academic.begin_grade_command(actor,kind,operation_key,jsonb_build_object('window',window_id,'target',target)); if prior is not null then return query select prior,target::text; return; end if;
 select * into w from academic.grade_capture_windows where id=window_id for update; valid:=(w.status='DRAFT' and target in ('OPEN','CANCELLED')) or (w.status='OPEN' and target in ('CLOSED','CANCELLED')); if w.id is null or not valid then raise exception 'GRADE_WINDOW_INVALID_STATE'; end if;
 perform set_config('academic.grade_controlled_mutation','on',true); update academic.grade_capture_windows set status=target,opened_by_account_id=case when target='OPEN' then actor else opened_by_account_id end,opened_at=case when target='OPEN' then statement_timestamp() else opened_at end,closed_by_account_id=case when target='CLOSED' then actor else closed_by_account_id end,closed_at=case when target='CLOSED' then statement_timestamp() else closed_at end,updated_at=statement_timestamp() where id=window_id; perform set_config('academic.grade_controlled_mutation','off',true);
 perform academic.complete_grade_command(actor,kind,operation_key,'GRADE_WINDOW',window_id); perform academic.append_grade_event(null,'GRADE_WINDOW',window_id,event,actor,w.status::text,target::text,operation_key,correlation); return query select window_id,target::text; end$$;
create function academic.open_grade_capture_window(id uuid,key text,correlation uuid default null) returns table(entity_id uuid,status text) language sql security definer set search_path='' as $$select * from academic.change_grade_window_status(id,'OPEN','OPEN_WINDOW','GRADE_WINDOW_OPENED',key,correlation)$$;
create function academic.close_grade_capture_window(id uuid,key text,correlation uuid default null) returns table(entity_id uuid,status text) language sql security definer set search_path='' as $$select * from academic.change_grade_window_status(id,'CLOSED','CLOSE_WINDOW','GRADE_WINDOW_CLOSED',key,correlation)$$;
create function academic.cancel_grade_capture_window(id uuid,key text,correlation uuid default null) returns table(entity_id uuid,status text) language sql security definer set search_path='' as $$select * from academic.change_grade_window_status(id,'CANCELLED','CANCEL_WINDOW','GRADE_WINDOW_CANCELLED',key,correlation)$$;

create function academic.capture_student_unit_grade(offering_enrollment_id uuid,subject_unit_id uuid,raw_grade numeric,operation_key text,correlation uuid default null) returns table(entity_id uuid,status text) language plpgsql security definer set search_path='' as $$
declare actor uuid; prior uuid; created uuid; data record; unit smallint; begin actor:=academic.require_grade_permission('academic.grades.capture'); prior:=academic.begin_grade_command(actor,'CAPTURE_GRADE',operation_key,jsonb_build_object('enrollment',offering_enrollment_id,'unit',subject_unit_id,'grade',raw_grade)); if prior is not null then return query select prior,'CAPTURED'; return; end if;
 if raw_grade<0 or raw_grade>10 then raise exception 'INVALID_GRADE_VALUE'; end if;
 select soe.id,soe.academic_offering_id,pe.id period_enrollment_id,pe.student_record_id,o.academic_period_id,o.curriculum_subject_id,soe.status offering_status,pe.status enrollment_status into data from academic.student_offering_enrollments soe join academic.period_enrollments pe on pe.id=soe.period_enrollment_id join academic.academic_offerings o on o.id=soe.academic_offering_id where soe.id=offering_enrollment_id for update of soe,pe,o;
 if data.id is null or data.offering_status<>'ACTIVE' or data.enrollment_status<>'ACTIVE' then raise exception 'STUDENT_NOT_ENROLLED'; end if;
 select su.unit_number into unit from academic.subject_units su where su.id=subject_unit_id and su.curriculum_subject_id=data.curriculum_subject_id; if unit is null or unit not between 1 and 3 then raise exception 'SUBJECT_UNIT_NOT_COMPATIBLE'; end if;
 if not exists(select 1 from academic.grade_capture_windows w where w.academic_period_id=data.academic_period_id and w.window_type='UNIT_CAPTURE' and w.unit_number=unit and w.status='OPEN' and statement_timestamp() between w.opens_at and w.closes_at) then raise exception 'GRADE_WINDOW_NOT_OPEN'; end if;
 if exists(select 1 from core.account_roles ar join core.roles r on r.id=ar.role_id where ar.account_id=actor and ar.revoked_at is null and r.code='DOCENTE') and not exists(select 1 from academic.teaching_assignments a where a.academic_offering_id=data.academic_offering_id and a.teacher_account_id=actor and a.status='ACTIVE') then raise exception 'TEACHER_NOT_AUTHORIZED'; end if;
 insert into academic.student_unit_grades(student_record_id,period_enrollment_id,student_offering_enrollment_id,academic_offering_id,subject_unit_id,unit_number,raw_grade,normalized_grade,is_accredited,captured_by_account_id) values(data.student_record_id,data.period_enrollment_id,offering_enrollment_id,data.academic_offering_id,subject_unit_id,unit,raw_grade,raw_grade,raw_grade>=6,actor) returning id into created;
 insert into academic.student_unit_grade_history(student_unit_grade_id,resulting_raw_grade,resulting_status,actor_account_id,reason_code) values(created,raw_grade,'CAPTURED',actor,'INITIAL_CAPTURE'); perform academic.complete_grade_command(actor,'CAPTURE_GRADE',operation_key,'UNIT_GRADE',created); perform academic.append_grade_event(data.student_record_id,'UNIT_GRADE',created,'UNIT_GRADE_CAPTURED',actor,null,'CAPTURED',operation_key,correlation); return query select created,'CAPTURED';
exception when unique_violation then raise exception 'UNIT_GRADE_ALREADY_EXISTS'; end$$;
create function academic.capture_bulk_unit_grades(items jsonb,operation_key text,correlation uuid default null) returns table(entity_id uuid,status text) language plpgsql security definer set search_path='' as $$declare actor uuid; prior uuid; item jsonb; last_id uuid; begin actor:=academic.require_grade_permission('academic.grades.capture'); prior:=academic.begin_grade_command(actor,'CAPTURE_BULK_GRADES',operation_key,items); if prior is not null then return query select prior,'CAPTURED'; return; end if; if jsonb_typeof(items)<>'array' or jsonb_array_length(items)=0 then raise exception 'INVALID_GRADE_VALUE'; end if; for item in select value from jsonb_array_elements(items) loop select captured.entity_id into last_id from academic.capture_student_unit_grade((item->>'student_offering_enrollment_id')::uuid,(item->>'subject_unit_id')::uuid,(item->>'raw_grade')::numeric,operation_key||'_'||(item->>'subject_unit_id'),correlation) captured; end loop; perform academic.complete_grade_command(actor,'CAPTURE_BULK_GRADES',operation_key,'UNIT_GRADE',last_id); perform academic.append_grade_event(null,'UNIT_GRADE',last_id,'BULK_UNIT_GRADES_CAPTURED',actor,null,'CAPTURED',operation_key,correlation); return query select last_id,'CAPTURED'; end$$;
create function academic.change_unit_grade_status(grade_id uuid,target academic.unit_grade_status,kind academic.grade_command_type,event academic.grade_event_type,permission text,operation_key text,correlation uuid) returns table(entity_id uuid,status text) language plpgsql security definer set search_path='' as $$
declare actor uuid; prior uuid; g academic.student_unit_grades%rowtype; valid boolean; begin actor:=academic.require_grade_permission(permission); prior:=academic.begin_grade_command(actor,kind,operation_key,jsonb_build_object('grade',grade_id,'target',target)); if prior is not null then return query select prior,target::text; return; end if; select * into g from academic.student_unit_grades where id=grade_id for update;
 valid:=(g.status='CAPTURED' and target='REVIEWED') or (g.status='REVIEWED' and target='FINALIZED') or (g.status in ('DRAFT','CAPTURED') and target='CANCELLED'); if g.id is null or not valid then raise exception 'UNIT_GRADE_INVALID_STATE'; end if;
 if exists(select 1 from core.account_roles ar join core.roles r on r.id=ar.role_id where ar.account_id=actor and ar.revoked_at is null and r.code='DOCENTE') and not exists(select 1 from academic.teaching_assignments a where a.academic_offering_id=g.academic_offering_id and a.teacher_account_id=actor and a.status='ACTIVE') then raise exception 'TEACHER_NOT_AUTHORIZED'; end if;
 perform set_config('academic.grade_controlled_mutation','on',true); update academic.student_unit_grades set status=target,reviewed_by_account_id=case when target='REVIEWED' then actor else reviewed_by_account_id end,reviewed_at=case when target='REVIEWED' then statement_timestamp() else reviewed_at end,finalized_by_account_id=case when target='FINALIZED' then actor else finalized_by_account_id end,finalized_at=case when target='FINALIZED' then statement_timestamp() else finalized_at end,updated_at=statement_timestamp() where id=grade_id; perform set_config('academic.grade_controlled_mutation','off',true);
 insert into academic.student_unit_grade_history(student_unit_grade_id,previous_raw_grade,resulting_raw_grade,previous_status,resulting_status,actor_account_id,reason_code) values(g.id,g.raw_grade,g.raw_grade,g.status,target,actor,'STATUS_CHANGE'); perform academic.complete_grade_command(actor,kind,operation_key,'UNIT_GRADE',grade_id); perform academic.append_grade_event(g.student_record_id,'UNIT_GRADE',grade_id,event,actor,g.status::text,target::text,operation_key,correlation); return query select grade_id,target::text; end$$;
create function academic.review_student_unit_grade(id uuid,key text,correlation uuid default null) returns table(entity_id uuid,status text) language sql security definer set search_path='' as $$select * from academic.change_unit_grade_status(id,'REVIEWED','REVIEW_GRADE','UNIT_GRADE_REVIEWED','academic.grades.review',key,correlation)$$;
create function academic.finalize_student_unit_grade(id uuid,key text,correlation uuid default null) returns table(entity_id uuid,status text) language sql security definer set search_path='' as $$select * from academic.change_unit_grade_status(id,'FINALIZED','FINALIZE_GRADE','UNIT_GRADE_FINALIZED','academic.grades.finalize',key,correlation)$$;
create function academic.cancel_student_unit_grade(id uuid,key text,correlation uuid default null) returns table(entity_id uuid,status text) language sql security definer set search_path='' as $$select * from academic.change_unit_grade_status(id,'CANCELLED','CANCEL_GRADE','OPERATION_REJECTED','academic.grades.correct',key,correlation)$$;

create function academic.calculate_subject_final_result(offering_enrollment_id uuid,operation_key text,correlation uuid default null) returns table(entity_id uuid,status text) language plpgsql security definer set search_path='' as $$
declare actor uuid; prior uuid; data record; created uuid; ac smallint; na smallint; prior_result academic.subject_final_results%rowtype; begin actor:=academic.require_grade_permission('academic.subject_results.calculate'); prior:=academic.begin_grade_command(actor,'CALCULATE_SUBJECT_RESULT',operation_key,jsonb_build_object('enrollment',offering_enrollment_id)); if prior is not null then return query select prior,'CALCULATED'; return; end if;
 select soe.academic_offering_id,pe.id period_enrollment_id,pe.student_record_id into data from academic.student_offering_enrollments soe join academic.period_enrollments pe on pe.id=soe.period_enrollment_id where soe.id=offering_enrollment_id for update of soe,pe; select count(*) filter(where g.is_accredited)::smallint,count(*) filter(where not g.is_accredited)::smallint into ac,na from academic.student_unit_grades g where g.student_offering_enrollment_id=offering_enrollment_id and g.status in ('FINALIZED','CORRECTED'); if ac+na<>3 then raise exception 'UNIT_GRADES_INCOMPLETE'; end if;
 select * into prior_result from academic.subject_final_results where student_offering_enrollment_id=offering_enrollment_id for update; perform set_config('academic.grade_controlled_mutation','on',true);
 if prior_result.id is null then insert into academic.subject_final_results(student_record_id,period_enrollment_id,student_offering_enrollment_id,academic_offering_id,accredited_unit_count,non_accredited_unit_count,result_code,calculation_status,status,calculated_by_account_id) values(data.student_record_id,data.period_enrollment_id,offering_enrollment_id,data.academic_offering_id,ac,na,case when ac>=2 then 'AC'::academic.subject_result_code else 'NA'::academic.subject_result_code end,'MANUAL_REVIEW_REQUIRED','CALCULATED',actor) returning id into created;
 else update academic.subject_final_results set accredited_unit_count=ac,non_accredited_unit_count=na,result_code=case when ac>=2 then 'AC'::academic.subject_result_code else 'NA'::academic.subject_result_code end,calculation_status='MANUAL_REVIEW_REQUIRED',status=case when academic.subject_final_results.status='CONFIRMED' then 'CORRECTED'::academic.subject_result_status else 'CALCULATED'::academic.subject_result_status end,calculated_by_account_id=actor,calculated_at=statement_timestamp(),updated_at=statement_timestamp() where id=prior_result.id returning id into created; end if; perform set_config('academic.grade_controlled_mutation','off',true);
 insert into academic.subject_result_history(subject_final_result_id,previous_result,resulting_result,previous_status,resulting_status,actor_account_id) values(created,prior_result.result_code,case when ac>=2 then 'AC'::academic.subject_result_code else 'NA'::academic.subject_result_code end,prior_result.status,'CALCULATED',actor); perform academic.complete_grade_command(actor,'CALCULATE_SUBJECT_RESULT',operation_key,'SUBJECT_RESULT',created); perform academic.append_grade_event(data.student_record_id,'SUBJECT_RESULT',created,'SUBJECT_RESULT_CALCULATED',actor,prior_result.status::text,'CALCULATED',operation_key,correlation); return query select created,'CALCULATED'; end$$;
create function academic.confirm_subject_final_result(result_id uuid,operation_key text,correlation uuid default null) returns table(entity_id uuid,status text) language plpgsql security definer set search_path='' as $$declare actor uuid; r academic.subject_final_results%rowtype; begin actor:=academic.require_grade_permission('academic.subject_results.confirm'); select * into r from academic.subject_final_results where id=result_id for update; if r.id is null or r.status<>'CALCULATED' then raise exception 'SUBJECT_RESULT_INVALID_STATE'; end if; perform set_config('academic.grade_controlled_mutation','on',true); update academic.subject_final_results set status='CONFIRMED',confirmed_by_account_id=actor,confirmed_at=statement_timestamp(),updated_at=statement_timestamp() where id=result_id; perform set_config('academic.grade_controlled_mutation','off',true); insert into academic.subject_result_history(subject_final_result_id,previous_result,resulting_result,previous_status,resulting_status,actor_account_id) values(r.id,r.result_code,r.result_code,r.status,'CONFIRMED',actor); perform academic.append_grade_event(r.student_record_id,'SUBJECT_RESULT',r.id,'SUBJECT_RESULT_CONFIRMED',actor,'CALCULATED','CONFIRMED',operation_key,correlation); return query select r.id,'CONFIRMED'; end$$;

create function academic.calculate_semester_evaluation_summary(enrollment_id uuid,operation_key text,correlation uuid default null) returns table(entity_id uuid,status text) language plpgsql security definer set search_path='' as $$
declare actor uuid; pe academic.period_enrollments%rowtype; total integer; ac integer; na integer; pending integer; created uuid; begin actor:=academic.require_grade_permission('academic.semester_evaluations.calculate'); select * into pe from academic.period_enrollments where id=enrollment_id for update; if pe.id is null then raise exception 'STUDENT_NOT_ENROLLED'; end if;
 select count(*) into total from academic.student_offering_enrollments soe_count where soe_count.period_enrollment_id=pe.id and soe_count.status in ('ACTIVE','COMPLETED'); select count(*) filter(where r.result_code='AC'),count(*) filter(where r.result_code='NA') into ac,na from academic.student_offering_enrollments soe left join academic.subject_final_results r on r.student_offering_enrollment_id=soe.id and r.status in ('CALCULATED','CONFIRMED','CORRECTED') where soe.period_enrollment_id=pe.id and soe.status in ('ACTIVE','COMPLETED'); pending:=total-ac-na;
 perform set_config('academic.grade_controlled_mutation','on',true); insert into academic.semester_evaluation_summaries(student_record_id,period_enrollment_id,academic_period_id,semester_number,total_subject_count,accredited_subject_count,non_accredited_subject_count,pending_subject_count,evaluation_status,proposed_progress_decision,proposal_reason_code,calculated_by_account_id) values(pe.student_record_id,pe.id,pe.academic_period_id,pe.semester_number,total,ac,na,pending,case when pending>0 then 'INCOMPLETE'::academic.semester_evaluation_status else 'MANUAL_REVIEW_REQUIRED'::academic.semester_evaluation_status end,'MANUAL_REVIEW_REQUIRED',case when pending>0 then 'SUBJECT_RESULTS_PENDING'::academic.grade_proposal_reason when na>0 then 'NON_ACCREDITED_SUBJECTS_REQUIRE_POLICY'::academic.grade_proposal_reason else 'INSTITUTIONAL_REVIEW'::academic.grade_proposal_reason end,actor) on conflict(period_enrollment_id) do update set total_subject_count=excluded.total_subject_count,accredited_subject_count=excluded.accredited_subject_count,non_accredited_subject_count=excluded.non_accredited_subject_count,pending_subject_count=excluded.pending_subject_count,evaluation_status=excluded.evaluation_status,proposed_progress_decision=excluded.proposed_progress_decision,proposal_reason_code=excluded.proposal_reason_code,calculated_by_account_id=actor,calculated_at=statement_timestamp(),updated_at=statement_timestamp() returning id into created; perform set_config('academic.grade_controlled_mutation','off',true);
 perform academic.append_grade_event(pe.student_record_id,'SEMESTER_SUMMARY',created,'SEMESTER_EVALUATION_CALCULATED',actor,null,case when pending>0 then 'INCOMPLETE' else 'MANUAL_REVIEW_REQUIRED' end,operation_key,correlation); return query select created,case when pending>0 then 'INCOMPLETE' else 'MANUAL_REVIEW_REQUIRED' end; end$$;
create function academic.confirm_semester_progress_decision(summary_id uuid,operation_key text,correlation uuid default null) returns table(entity_id uuid,status text) language plpgsql security definer set search_path='' as $$declare actor uuid; s academic.semester_evaluation_summaries%rowtype; pe academic.period_enrollments%rowtype; decision_id uuid; begin actor:=academic.require_grade_permission('academic.progress_decisions.confirm'); select * into s from academic.semester_evaluation_summaries where id=summary_id for update; if s.id is null or s.evaluation_status not in ('COMPLETE','MANUAL_REVIEW_REQUIRED') then raise exception 'SEMESTER_EVALUATION_INCOMPLETE'; end if; if s.proposed_progress_decision='MANUAL_REVIEW_REQUIRED' then raise exception 'PROGRESS_DECISION_REQUIRES_REVIEW'; end if; select * into pe from academic.period_enrollments where id=s.period_enrollment_id for update; insert into academic.academic_progress_decisions(student_record_id,source_period_enrollment_id,source_academic_period_id,decision_type,resulting_semester_number,resulting_training_area_id,reason_code,decided_by_account_id,approved_by_account_id,idempotency_key,request_fingerprint) values(s.student_record_id,s.period_enrollment_id,s.academic_period_id,s.proposed_progress_decision::text::academic.progress_decision_type,case when s.proposed_progress_decision='ADVANCE' then least(pe.semester_number+1,6) else pe.semester_number end,pe.training_area_id,'INSTITUTIONAL_VALIDATION_PENDING',actor,actor,operation_key,academic.grade_fingerprint(jsonb_build_object('summary',summary_id,'proposal',s.proposed_progress_decision))) returning id into decision_id; perform set_config('academic.grade_controlled_mutation','on',true); update academic.semester_evaluation_summaries set evaluation_status='CONFIRMED',confirmed_by_account_id=actor,confirmed_at=statement_timestamp(),progress_decision_id=decision_id,updated_at=statement_timestamp() where id=s.id; perform set_config('academic.grade_controlled_mutation','off',true); perform academic.append_grade_event(s.student_record_id,'PROGRESS_DECISION',decision_id,'PROGRESS_DECISION_CONFIRMED',actor,s.evaluation_status::text,'CONFIRMED',operation_key,correlation); return query select decision_id,'CONFIRMED'; end$$;

create function academic.get_student_subject_grade_summary(p_offering_enrollment_id uuid) returns table(finalized_unit_count integer,accredited_unit_count integer,result_code academic.subject_result_code,calculation_status academic.grade_calculation_status) language plpgsql stable security definer set search_path='' as $$begin perform academic.require_grade_permission('academic.subject_results.read'); return query select count(*) filter(where g.status in ('FINALIZED','CORRECTED'))::integer,count(*) filter(where g.status in ('FINALIZED','CORRECTED') and g.is_accredited)::integer,r.result_code,r.calculation_status from academic.student_unit_grades g left join academic.subject_final_results r on r.student_offering_enrollment_id=g.student_offering_enrollment_id where g.student_offering_enrollment_id=p_offering_enrollment_id group by r.result_code,r.calculation_status; end$$;
create function academic.get_student_semester_evaluation_summary(p_period_enrollment_id uuid) returns table(total_subject_count integer,accredited_subject_count integer,non_accredited_subject_count integer,pending_subject_count integer,evaluation_status academic.semester_evaluation_status,proposed_progress_decision academic.progress_proposal) language plpgsql stable security definer set search_path='' as $$begin perform academic.require_grade_permission('academic.semester_evaluations.read'); return query select s.total_subject_count,s.accredited_subject_count,s.non_accredited_subject_count,s.pending_subject_count,s.evaluation_status,s.proposed_progress_decision from academic.semester_evaluation_summaries s where s.period_enrollment_id=p_period_enrollment_id; end$$;
create function academic.validate_grade_capture_integrity(p_offering_enrollment_id uuid) returns table(valid boolean,unit_count integer,duplicate_count integer) language plpgsql stable security definer set search_path='' as $$begin perform academic.require_grade_permission('academic.grades.read'); return query select count(*)<=3,count(*)::integer,(count(*)-count(distinct g.unit_number))::integer from academic.student_unit_grades g where g.student_offering_enrollment_id=p_offering_enrollment_id; end$$;
create function academic.validate_subject_unit_completion(p_offering_enrollment_id uuid) returns table(complete boolean,finalized_count integer) language plpgsql stable security definer set search_path='' as $$begin perform academic.require_grade_permission('academic.subject_results.read'); return query select count(*) filter(where g.status in ('FINALIZED','CORRECTED'))=3,count(*) filter(where g.status in ('FINALIZED','CORRECTED'))::integer from academic.student_unit_grades g where g.student_offering_enrollment_id=p_offering_enrollment_id; end$$;

create function academic.create_grade_correction(grade_id uuid,proposed numeric,reason academic.grade_correction_reason,operation_key text,correlation uuid default null) returns table(entity_id uuid,status text) language plpgsql security definer set search_path='' as $$declare actor uuid; g academic.student_unit_grades%rowtype; created uuid; begin actor:=academic.require_grade_permission('academic.grades.correct'); if proposed<0 or proposed>10 then raise exception 'INVALID_GRADE_VALUE'; end if; select * into g from academic.student_unit_grades where id=grade_id for update; if g.id is null or g.status not in ('FINALIZED','CORRECTED') then raise exception 'GRADE_CORRECTION_INVALID_STATE'; end if; insert into academic.grade_corrections(student_unit_grade_id,previous_raw_grade,proposed_raw_grade,reason_code,requested_by_account_id,idempotency_key,request_fingerprint) values(g.id,g.raw_grade,proposed,reason,actor,operation_key,academic.grade_fingerprint(jsonb_build_object('grade',grade_id,'proposed',proposed,'reason',reason))) returning id into created; perform academic.append_grade_event(g.student_record_id,'GRADE_CORRECTION',created,'GRADE_CORRECTION_CREATED',actor,null,'DRAFT',operation_key,correlation); return query select created,'DRAFT'; end$$;
create function academic.change_grade_correction_status(correction_id uuid,target academic.grade_correction_status,operation_key text,correlation uuid) returns table(entity_id uuid,status text) language plpgsql security definer set search_path='' as $$declare actor uuid; c academic.grade_corrections%rowtype; g academic.student_unit_grades%rowtype; valid boolean; begin actor:=academic.require_grade_permission('academic.grades.correct'); select * into c from academic.grade_corrections where id=correction_id for update; valid:=(c.status='DRAFT' and target in ('SUBMITTED','CANCELLED')) or (c.status='SUBMITTED' and target in ('UNDER_REVIEW','CANCELLED')) or (c.status='UNDER_REVIEW' and target in ('APPROVED','REJECTED')) or (c.status='APPROVED' and target='APPLIED'); if c.id is null or not valid then raise exception 'GRADE_CORRECTION_INVALID_STATE'; end if; select * into g from academic.student_unit_grades where id=c.student_unit_grade_id for update; perform set_config('academic.grade_controlled_mutation','on',true); update academic.grade_corrections set status=target,reviewed_by_account_id=case when target='UNDER_REVIEW' then actor else reviewed_by_account_id end,approved_by_account_id=case when target='APPROVED' then actor else approved_by_account_id end,applied_by_account_id=case when target='APPLIED' then actor else applied_by_account_id end,reviewed_at=case when target='UNDER_REVIEW' then statement_timestamp() else reviewed_at end,approved_at=case when target='APPROVED' then statement_timestamp() else approved_at end,applied_at=case when target='APPLIED' then statement_timestamp() else applied_at end,rejected_at=case when target='REJECTED' then statement_timestamp() else rejected_at end,cancelled_at=case when target='CANCELLED' then statement_timestamp() else cancelled_at end,updated_at=statement_timestamp() where id=c.id; if target='APPLIED' then update academic.student_unit_grades set raw_grade=c.proposed_raw_grade,normalized_grade=c.proposed_raw_grade,is_accredited=c.proposed_raw_grade>=6,status='CORRECTED',updated_at=statement_timestamp() where id=g.id; insert into academic.student_unit_grade_history(student_unit_grade_id,previous_raw_grade,resulting_raw_grade,previous_status,resulting_status,actor_account_id,reason_code,correction_id) values(g.id,g.raw_grade,c.proposed_raw_grade,g.status,'CORRECTED',actor,c.reason_code::text,c.id); end if; perform set_config('academic.grade_controlled_mutation','off',true); if target in ('APPROVED','APPLIED') then perform academic.append_grade_event(g.student_record_id,'GRADE_CORRECTION',c.id,case when target='APPROVED' then 'GRADE_CORRECTION_APPROVED'::academic.grade_event_type else 'GRADE_CORRECTION_APPLIED'::academic.grade_event_type end,actor,c.status::text,target::text,operation_key,correlation); end if; return query select c.id,target::text; end$$;
create function academic.submit_grade_correction(id uuid,key text,correlation uuid default null) returns table(entity_id uuid,status text) language sql security definer set search_path='' as $$select * from academic.change_grade_correction_status(id,'SUBMITTED',key,correlation)$$;
create function academic.begin_grade_correction_review(id uuid,key text,correlation uuid default null) returns table(entity_id uuid,status text) language sql security definer set search_path='' as $$select * from academic.change_grade_correction_status(id,'UNDER_REVIEW',key,correlation)$$;
create function academic.approve_grade_correction(id uuid,key text,correlation uuid default null) returns table(entity_id uuid,status text) language sql security definer set search_path='' as $$select * from academic.change_grade_correction_status(id,'APPROVED',key,correlation)$$;
create function academic.reject_grade_correction(id uuid,key text,correlation uuid default null) returns table(entity_id uuid,status text) language sql security definer set search_path='' as $$select * from academic.change_grade_correction_status(id,'REJECTED',key,correlation)$$;
create function academic.apply_grade_correction(id uuid,key text,correlation uuid default null) returns table(entity_id uuid,status text) language sql security definer set search_path='' as $$select * from academic.change_grade_correction_status(id,'APPLIED',key,correlation)$$;
create function academic.cancel_grade_correction(id uuid,key text,correlation uuid default null) returns table(entity_id uuid,status text) language sql security definer set search_path='' as $$select * from academic.change_grade_correction_status(id,'CANCELLED',key,correlation)$$;

create function academic.guard_grade_immutable() returns trigger language plpgsql security invoker set search_path='' as $$begin if tg_op='DELETE' then raise exception 'HISTORICAL_GRADE_IMMUTABLE'; end if; if current_setting('academic.grade_controlled_mutation',true)<>'on' and old is distinct from new then raise exception 'HISTORICAL_GRADE_IMMUTABLE'; end if; return new; end$$;
create trigger grade_windows_immutable before update or delete on academic.grade_capture_windows for each row execute function academic.guard_grade_immutable();
create trigger unit_grades_immutable before update or delete on academic.student_unit_grades for each row execute function academic.guard_grade_immutable();
create trigger unit_grade_history_immutable before update or delete on academic.student_unit_grade_history for each row execute function academic.guard_grade_immutable();
create trigger subject_results_immutable before update or delete on academic.subject_final_results for each row execute function academic.guard_grade_immutable();
create trigger subject_result_history_immutable before update or delete on academic.subject_result_history for each row execute function academic.guard_grade_immutable();
create trigger semester_summaries_immutable before update or delete on academic.semester_evaluation_summaries for each row execute function academic.guard_grade_immutable();
create trigger grade_corrections_immutable before update or delete on academic.grade_corrections for each row execute function academic.guard_grade_immutable();
create trigger grade_commands_immutable before delete on academic.grade_commands for each row execute function academic.guard_grade_immutable();
create trigger grade_events_immutable before update or delete on academic.grade_events for each row execute function academic.guard_grade_immutable();
create function academic.guard_grade_source_dependencies() returns trigger language plpgsql security invoker set search_path='' as $$begin if old is not distinct from new then return new; end if; if tg_table_name='academic_periods' then if exists(select 1 from academic.grade_capture_windows w where w.academic_period_id=old.id and w.status='OPEN') then raise exception 'CONCURRENT_MODIFICATION'; end if; elsif tg_table_name='period_enrollments' then if exists(select 1 from academic.student_unit_grades g where g.period_enrollment_id=old.id and g.status<>'CANCELLED') then raise exception 'CONCURRENT_MODIFICATION'; end if; elsif tg_table_name='teaching_assignments' then if exists(select 1 from academic.student_unit_grades g where g.academic_offering_id=old.academic_offering_id and g.status<>'CANCELLED') then raise exception 'CONCURRENT_MODIFICATION'; end if; end if; return new; end$$;
create trigger period_grade_dependency before update on academic.academic_periods for each row execute function academic.guard_grade_source_dependencies();
create trigger enrollment_grade_dependency before update on academic.period_enrollments for each row execute function academic.guard_grade_source_dependencies();
create trigger assignment_grade_dependency before update on academic.teaching_assignments for each row execute function academic.guard_grade_source_dependencies();

alter table academic.grade_capture_windows enable row level security; alter table academic.student_unit_grades enable row level security; alter table academic.student_unit_grade_history enable row level security;
alter table academic.subject_final_results enable row level security; alter table academic.subject_result_history enable row level security; alter table academic.semester_evaluation_summaries enable row level security;
alter table academic.grade_corrections enable row level security; alter table academic.grade_commands enable row level security; alter table academic.grade_events enable row level security;
revoke all on academic.grade_capture_windows,academic.student_unit_grades,academic.student_unit_grade_history,academic.subject_final_results,academic.subject_result_history,academic.semester_evaluation_summaries,academic.grade_corrections,academic.grade_commands,academic.grade_events from public,anon,authenticated;
revoke all on all sequences in schema academic from public,anon,authenticated;
revoke all on all functions in schema academic from public,anon,authenticated;

commit;
